application:
  name: "games-api"


spring:
  mvc:
    pathmatch:
      matching-strategy : ant-path-matcher

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false
  main:
    banner-mode: off

server:
  port: 8080
  servlet:
    context-path: ${CONTEXT_PATH:/games}